// <auto-generated />
using System;
using AerolineaRD.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AerolineaRD.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251121041015_RefactorAeronave")]
    partial class RefactorAeronave
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.21");

            modelBuilder.Entity("AerolineaRD.Entity.Aeronave", b =>
                {
                    b.Property<string>("Matricula")
                        .HasMaxLength(15)
                        .HasColumnType("TEXT")
                        .HasColumnName("Matricula");

                    b.Property<int>("Capacidad")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Capacidad");

                    b.Property<string>("Estado")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("Estado");

                    b.Property<string>("Modelo")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("Modelo");

                    b.HasKey("Matricula");

                    b.ToTable("Aeronave");
                });

            modelBuilder.Entity("AerolineaRD.Entity.Aeropuerto", b =>
                {
                    b.Property<string>("Codigo")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("CodAeropuerto");

                    b.Property<string>("Ciudad")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("Ciudad");

                    b.Property<string>("Nombre")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("Nombre");

                    b.Property<string>("Pais")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("Pais");

                    b.HasKey("Codigo");

                    b.ToTable("Aeropuerto");
                });

            modelBuilder.Entity("AerolineaRD.Entity.Asiento", b =>
                {
                    b.Property<string>("Numero")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("NumAsiento");

                    b.Property<string>("Clase")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("Clase");

                    b.Property<string>("Matricula")
                        .HasMaxLength(15)
                        .HasColumnType("TEXT")
                        .HasColumnName("Matricula");

                    b.Property<string>("NumeroAsiento")
                        .HasMaxLength(5)
                        .HasColumnType("TEXT")
                        .HasColumnName("NumeroAsiento");

                    b.HasKey("Numero");

                    b.HasIndex("Matricula");

                    b.ToTable("Asiento");
                });

            modelBuilder.Entity("AerolineaRD.Entity.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("IdCliente");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("Email");

                    b.Property<string>("Nombre")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("Nombre");

                    b.Property<string>("Telefono")
                        .HasMaxLength(15)
                        .HasColumnType("TEXT")
                        .HasColumnName("Telefono");

                    b.Property<string>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("AerolineaRD.Entity.Equipaje", b =>
                {
                    b.Property<string>("Numero")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("NumEquipaje");

                    b.Property<int>("IdPasajero")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IdPasajero");

                    b.Property<decimal>("Peso")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("Peso");

                    b.Property<string>("Tipo")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("Tipo");

                    b.HasKey("Numero");

                    b.HasIndex("IdPasajero");

                    b.ToTable("Equipaje");
                });

            modelBuilder.Entity("AerolineaRD.Entity.EstadoVuelo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("IdEstado");

                    b.Property<string>("Estado")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("Estado");

                    b.Property<DateTime?>("HoraLlegada")
                        .HasColumnType("TEXT")
                        .HasColumnName("HoraLlegada");

                    b.Property<DateTime>("HoraLlegadaProgramada")
                        .HasColumnType("TEXT")
                        .HasColumnName("HoraLlegadaProgramada");

                    b.Property<DateTime?>("HoraSalida")
                        .HasColumnType("TEXT")
                        .HasColumnName("HoraSalida");

                    b.Property<DateTime>("HoraSalidaProgramada")
                        .HasColumnType("TEXT")
                        .HasColumnName("HoraSalidaProgramada");

                    b.Property<int>("IdVuelo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IdVuelo");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("Observaciones");

                    b.Property<string>("Puerta")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("Puerta");

                    b.HasKey("Id");

                    b.HasIndex("IdVuelo")
                        .IsUnique();

                    b.ToTable("EstadoVuelo");
                });

            modelBuilder.Entity("AerolineaRD.Entity.Factura", b =>
                {
                    b.Property<string>("Codigo")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("CodFactura");

                    b.Property<string>("CodReserva")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("CodReserva");

                    b.Property<string>("EstadoPago")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("EstadoPago");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("TEXT")
                        .HasColumnName("FechaEmision");

                    b.Property<string>("MetodoPago")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("MetodoPago");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("Monto");

                    b.HasKey("Codigo");

                    b.HasIndex("CodReserva")
                        .IsUnique();

                    b.ToTable("Factura");
                });

            modelBuilder.Entity("AerolineaRD.Entity.Notificacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("IdNotificacion");

                    b.Property<DateTime>("FechaEnvio")
                        .HasColumnType("TEXT")
                        .HasColumnName("FechaEnvio");

                    b.Property<int>("IdCliente")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IdCliente");

                    b.Property<bool>("Leida")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Leida");

                    b.Property<string>("Mensaje")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("Mensaje");

                    b.Property<string>("Tipo")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("Tipo");

                    b.HasKey("Id");

                    b.HasIndex("IdCliente");

                    b.ToTable("Notificacion");
                });

            modelBuilder.Entity("AerolineaRD.Entity.Pasajero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("IdPasajero");

                    b.Property<string>("Apellido")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("Apellido");

                    b.Property<string>("Nombre")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("Nombre");

                    b.Property<string>("Pasaporte")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("Pasaporte");

                    b.HasKey("Id");

                    b.ToTable("Pasajero");
                });

            modelBuilder.Entity("AerolineaRD.Entity.Reserva", b =>
                {
                    b.Property<string>("Codigo")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("CodReserva");

                    b.Property<string>("Clase")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("Clase");

                    b.Property<string>("Estado")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("Estado");

                    b.Property<DateTime>("FechaReserva")
                        .HasColumnType("date")
                        .HasColumnName("FechaReserva");

                    b.Property<int>("IdCliente")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IdCliente");

                    b.Property<int>("IdPasajero")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IdPasajero");

                    b.Property<int>("IdVuelo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IdVuelo");

                    b.Property<string>("NumAsiento")
                        .HasMaxLength(5)
                        .HasColumnType("TEXT")
                        .HasColumnName("NumAsiento");

                    b.Property<decimal>("PrecioTotal")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("PrecioTotal");

                    b.HasKey("Codigo");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdPasajero");

                    b.HasIndex("IdVuelo");

                    b.ToTable("Reserva");
                });

            modelBuilder.Entity("AerolineaRD.Entity.TicketSoporte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("IdTicket");

                    b.Property<string>("Asunto")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("Asunto");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("Descripcion");

                    b.Property<string>("Estado")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("Estado");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("TEXT")
                        .HasColumnName("FechaCierre");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT")
                        .HasColumnName("FechaCreacion");

                    b.Property<int>("IdCliente")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IdCliente");

                    b.Property<string>("Prioridad")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("Prioridad");

                    b.HasKey("Id");

                    b.HasIndex("IdCliente");

                    b.ToTable("TicketSoporte");
                });

            modelBuilder.Entity("AerolineaRD.Entity.Tripulacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("IdTripulacion");

                    b.Property<string>("Apellido")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("Apellido");

                    b.Property<string>("Licencia")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("Licencia");

                    b.Property<string>("Nombre")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("Nombre");

                    b.Property<string>("Rol")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("Rol");

                    b.HasKey("Id");

                    b.ToTable("Tripulacion");
                });

            modelBuilder.Entity("AerolineaRD.Entity.Vuelo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("IdVuelo");

                    b.Property<string>("ClasesDisponibles")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("ClasesDisponibles");

                    b.Property<string>("DestinoCodigo")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("Destino");

                    b.Property<int>("Duracion")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Duracion");

                    b.Property<string>("Estado")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("Estado");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("Fecha");

                    b.Property<DateTime?>("FechaRegreso")
                        .HasColumnType("TEXT")
                        .HasColumnName("FechaRegreso");

                    b.Property<TimeSpan>("HoraLlegada")
                        .HasColumnType("TEXT")
                        .HasColumnName("HoraLlegada");

                    b.Property<TimeSpan>("HoraSalida")
                        .HasColumnType("TEXT")
                        .HasColumnName("HoraSalida");

                    b.Property<string>("Matricula")
                        .HasMaxLength(15)
                        .HasColumnType("TEXT")
                        .HasColumnName("Matricula");

                    b.Property<string>("NumeroVuelo")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("NumeroVuelo");

                    b.Property<string>("OrigenCodigo")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("Origen");

                    b.Property<decimal>("PrecioBase")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("PrecioBase");

                    b.Property<string>("TipoVuelo")
                        .HasMaxLength(15)
                        .HasColumnType("TEXT")
                        .HasColumnName("TipoVuelo");

                    b.HasKey("Id");

                    b.HasIndex("DestinoCodigo");

                    b.HasIndex("Matricula");

                    b.HasIndex("OrigenCodigo");

                    b.ToTable("Vuelo");
                });

            modelBuilder.Entity("AerolineaRD.Entity.VueloTripulacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("IdVueloTripulacion");

                    b.Property<int>("IdTripulacion")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IdTripulacion");

                    b.Property<int>("IdVuelo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IdVuelo");

                    b.HasKey("Id");

                    b.HasIndex("IdTripulacion");

                    b.HasIndex("IdVuelo");

                    b.ToTable("VueloTripulacion", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("AerolineaRD.Entity.Asiento", b =>
                {
                    b.HasOne("AerolineaRD.Entity.Aeronave", "Aeronave")
                        .WithMany("Asientos")
                        .HasForeignKey("Matricula");

                    b.Navigation("Aeronave");
                });

            modelBuilder.Entity("AerolineaRD.Entity.Cliente", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AerolineaRD.Entity.Equipaje", b =>
                {
                    b.HasOne("AerolineaRD.Entity.Pasajero", "Pasajero")
                        .WithMany("Equipajes")
                        .HasForeignKey("IdPasajero")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pasajero");
                });

            modelBuilder.Entity("AerolineaRD.Entity.EstadoVuelo", b =>
                {
                    b.HasOne("AerolineaRD.Entity.Vuelo", "Vuelo")
                        .WithOne("EstadoVueloDetalle")
                        .HasForeignKey("AerolineaRD.Entity.EstadoVuelo", "IdVuelo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vuelo");
                });

            modelBuilder.Entity("AerolineaRD.Entity.Factura", b =>
                {
                    b.HasOne("AerolineaRD.Entity.Reserva", "Reserva")
                        .WithOne("Factura")
                        .HasForeignKey("AerolineaRD.Entity.Factura", "CodReserva");

                    b.Navigation("Reserva");
                });

            modelBuilder.Entity("AerolineaRD.Entity.Notificacion", b =>
                {
                    b.HasOne("AerolineaRD.Entity.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("AerolineaRD.Entity.Reserva", b =>
                {
                    b.HasOne("AerolineaRD.Entity.Cliente", "Cliente")
                        .WithMany("Reservas")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AerolineaRD.Entity.Pasajero", "Pasajero")
                        .WithMany("Reservas")
                        .HasForeignKey("IdPasajero")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AerolineaRD.Entity.Vuelo", "Vuelo")
                        .WithMany("Reservas")
                        .HasForeignKey("IdVuelo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Pasajero");

                    b.Navigation("Vuelo");
                });

            modelBuilder.Entity("AerolineaRD.Entity.TicketSoporte", b =>
                {
                    b.HasOne("AerolineaRD.Entity.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("AerolineaRD.Entity.Vuelo", b =>
                {
                    b.HasOne("AerolineaRD.Entity.Aeropuerto", "Destino")
                        .WithMany("VuelosDestino")
                        .HasForeignKey("DestinoCodigo");

                    b.HasOne("AerolineaRD.Entity.Aeronave", "Aeronave")
                        .WithMany("Vuelos")
                        .HasForeignKey("Matricula");

                    b.HasOne("AerolineaRD.Entity.Aeropuerto", "Origen")
                        .WithMany("VuelosOrigen")
                        .HasForeignKey("OrigenCodigo");

                    b.Navigation("Aeronave");

                    b.Navigation("Destino");

                    b.Navigation("Origen");
                });

            modelBuilder.Entity("AerolineaRD.Entity.VueloTripulacion", b =>
                {
                    b.HasOne("AerolineaRD.Entity.Tripulacion", "Tripulacion")
                        .WithMany()
                        .HasForeignKey("IdTripulacion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AerolineaRD.Entity.Vuelo", "Vuelo")
                        .WithMany()
                        .HasForeignKey("IdVuelo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tripulacion");

                    b.Navigation("Vuelo");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AerolineaRD.Entity.Aeronave", b =>
                {
                    b.Navigation("Asientos");

                    b.Navigation("Vuelos");
                });

            modelBuilder.Entity("AerolineaRD.Entity.Aeropuerto", b =>
                {
                    b.Navigation("VuelosDestino");

                    b.Navigation("VuelosOrigen");
                });

            modelBuilder.Entity("AerolineaRD.Entity.Cliente", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("AerolineaRD.Entity.Pasajero", b =>
                {
                    b.Navigation("Equipajes");

                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("AerolineaRD.Entity.Reserva", b =>
                {
                    b.Navigation("Factura");
                });

            modelBuilder.Entity("AerolineaRD.Entity.Vuelo", b =>
                {
                    b.Navigation("EstadoVueloDetalle");

                    b.Navigation("Reservas");
                });
#pragma warning restore 612, 618
        }
    }
}
